### ISSUE TITLE
It seem是

### ISSUE THREAD

**Issue by Anthea98** [nicgirault/circosJS#78] opened 2019-08-30 07:20 UTC

**Comment by Anthea98** [comment] 2019-08-30 07:22
It shows that .map is not a function……is this because it may conflict with the other d3 functions？

**Comment by nicgirault** [comment] 2019-08-30 17:25
Could you precise what is the variable on which you call `.map`? Providing a reproducible example would help to solve your problem.

I'll close this issue for now because I don't even understand the title of the issue. Feel free to re-open with more details.

**Closed as completed by nicgirault** 2019-08-30 17:25 UTC
